name: Deploy Docusaurus And Upload Artifacts

on:
  push:
    branches: # 直接推送至这些分支才会触发
      - main # 例如 main 分支
    types: # 只关注直接提交到分支的事件
      - ["push"] # 不包括 pull request 事件

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Docusaurus site
        run: npm run build

      - name: Get Timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +%s)"

      - name: Deploy Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Website-${{ steps.timestamp.outputs.timestamp }}
          path: build

      - name: List files in build directory
        run: ls -la build/

      - name: Deploy
        uses: easingthemes/ssh-deploy@v5.1.0
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
          ARGS: "-avz --delete"
          SOURCE: "build/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}
